### ISSUE TITLE
error

### ISSUE THREAD

**Issue by josep112** [ashishpahwa7/WhatsApp-AutoResponder#1]
I can not install I have the following error:

Double requirement given: lxml==3.6.4 (from -r requirements.txt (line 4)) (already in lxml==3.6.4 (from -r requirements.txt (line 1)), name='lxml')
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 275, in run
    requirement_set.add_requirement(req)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 989, in add_requirement
    % (install_req, self.get_requirement(name), name))
InstallationError: Double requirement given: lxml==3.6.4 (from -r requirements.txt (line 4)) (already in lxml==3.6.4 (from -r requirements.txt (line 1)), name='lxml')

**Comment by ashishpahwa7** [comment]
fixed
